spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/accounts
    driver-class-name: org.postgresql.Driver
    username: accounts
    password: accounts
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  jdbc:
    template:
      fetch-size: 10
      max-rows: 10
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      retries: 100
      batch-size: 32768
      buffer-memory:
      compression-type: snappy
      acks: all
      properties:
        enable-idempotence: true
        linger-ms: 20
        max-in-flight-requests-per-connection: 5
    consumer:
      bootstrap-servers: "127.0.0.1:9092"
      group-id: accounts
      max-poll-records: 2

elasticsearch:
  host: kafka-learning-2812223976.eu-central-1.bonsaisearch.net
  port: 443
  connect-timeout: 10000
  request-timeout: 30000
server:
  port: 8776
http-client:
  log-level: BASIC
  follow-redirects: true

jwt.jwks:
  publicKey: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz2ManhJsbnNiunl7Mgts
              7rQi3o8p2kApQGbvK9F0qgjxPeQ7Q8qbPp2KUazEIU2AoFyiabI0miQ5UA4sTm30
              Ox3TU6BtRWeYajDmVG4SVEfvk3rg3g2imQVAV2sBXc4HWF3n3oiCMauLqvBzR0ST
              M2sXzBCSpS6csYbpj41kK7uh9XyXjnMQ3WBG2sP/IpKaN2VWHqP4YZe7tmPpJ1DY
              jZXPbl8Fk2Z/1MTIOGT72V1KwCLh9wldUdWK/SNPncRfkZxbiona12JLKQS83lWH
              VQHy3I07NShd3qW0qGapxNC5KrHWuFAKFNK/9ISgXYDttY0aUkVraZ80RPofDwHH
              GwIDAQAB
              -----END PUBLIC KEY-----
  privateKey: |
              -----BEGIN PRIVATE KEY-----
              MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPYxqeEmxuc2K6
              eXsyC2zutCLejynaQClAZu8r0XSqCPE95DtDyps+nYpRrMQhTYCgXKJpsjSaJDlQ
              DixObfQ7HdNToG1FZ5hqMOZUbhJUR++TeuDeDaKZBUBXawFdzgdYXefeiIIxq4uq
              8HNHRJMzaxfMEJKlLpyxhumPjWQru6H1fJeOcxDdYEbaw/8ikpo3ZVYeo/hhl7u2
              Y+knUNiNlc9uXwWTZn/UxMg4ZPvZXUrAIuH3CV1R1Yr9I0+dxF+RnFuKidrXYksp
              BLzeVYdVAfLcjTs1KF3epbSoZqnE0Lkqsda4UAoU0r/0hKBdgO21jRpSRWtpnzRE
              +h8PAccbAgMBAAECggEAYYsilODjgVviPwUujc5T8T5m/DloHRB6lqETs490CRnl
              pg+4VF1ygZQF3/6bzXIvor2PYpmAJlQNZPsVmdobusZ/hGD7pF5ikOfpHiMbmeqv
              47UzGR5esQyIQ9W/schbKhQZIFEis4wVSFSKVCYL+m5PphrRbsIqz1E+f9eoGuzw
              MmBJnOOhG3LtxHh0YJLcPVq3kTTxk7aUUPzpt143upTkhhD7Aybv0FrDZDYw9MEP
              hzm7rFRDDlu6NIO7v1uDPi+QLiWcKgaKC6JbRFx+wYIzrgKrhtTwjDlYVsZnf9yp
              4Yf++XhnmPnbb7OUuUBkan2ptv4YGkmVN1SVq2+HgQKBgQDncymS8r/F157CmUtf
              xcsZR8saNZbBns6s4xjteZAyG8i06Rbkzro2JlRI85SMt5xJgeepCrubH4pxpS03
              xLnp8Si5+3RSQu8OTMVxFncbGAiFMn9MnIWGYXIovBfzxNovvNPKyHzgt2hUGNlQ
              FMwvBjyIu0r7JUq5k1mPIzcMwQKBgQDlYomIIdcBHblEnJMZlgo6Jq5mKqPNDvDB
              XEO135Dv/Iv5rubmvZB7rt3TWSovLQgq6Bk7JfUM3HBIq+ZgxdZwy7jZi4PFU0Z/
              ltKmyefQkfnPEBxrcLoZy15P9/phVkZmOy7sn5AMeiWlBlLBIg3I82GkWF5t57dB
              Duj29/te2wKBgQCjDM03+Y1COiFc5BNmd/gZaitZ3nDDHDZrM11HRsFfm5UsZZy8
              OiqSpTPxZK+85kjSvBJQUwBRSsoEP6H4TL3QYhUX2F5c6Uxx3YGmpnXn/2lZNHbb
              qNSkE5gRvFh/Yal3weXOUKkwweRcgljtgolJg3I3vQIYpW/cBkMshFluwQKBgCw9
              tQjsfetZMEJrcHOe3Joam8hYsP77wrOIeAa799hRfS3K7f3S0esI7v+0Us6GgOzF
              lxgxWfIBEibyAJzpi1J1+FD89403YoF5NWe1yWAQx32IPfL66unOr4H88e2UFj/h
              akt4+u9tH5WUgqF9T+tSBaMM6CmKZ23E0mnPqkvBAoGBANNp+UB371kOzWb+yA4X
              wDGFzDPnW+kc7zSj2XUF1I+jbKEaq/3EVEJ2PDiFJ+u09vc1GYSQNl+LgK6w7AvG
              Jr3dp1e7DIz1lmXmacsFPnM5eeX1s0IeuCywZX3cdIXBUzGGxdc2QXP02Ko/aGHz
              qCy3fOQx9iuXVxgjDV2Zg4AM
              -----END PRIVATE KEY-----

